version: 2
workflows:
  version: 2
  test:
    jobs:
      - emacs24.5
      - emacs25.1
      - emacs26.1
jobs:
  emacs24.5: &test-body
    steps:
      - checkout
      - run:
          name: Check Emacs version
          command: emacs --version
      - run:
          name: Make elc
          command: make elc
      - run:
          name: Testing
          command: make test
    docker:
      - image: silex/emacs:24.5-dev
  emacs25.1:
    <<: *test-body
    docker:
      - image: silex/emacs:25.1-dev
  emacs26.1:
    <<: *test-body
    docker:
      - image: silex/emacs:26.1-dev
